# Nombre y puerto del microservicio (usaremos el 8082 para que no choque con los otros)
spring.application.name=ms-pacientes-db
server.port=8082

# Conexión a la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_pacientes_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Configuración de Hibernate/JPA (crea las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true